import { RecommendationRequestStatus } from "@music-recommender/shared";
import { query } from "../db/client.js";

export async function markRecommendationRequestRunning(requestId: string) {
  await query(
    `
      update recommendation_requests
      set status = $2, error_message = null
      where id = $1
    `,
    [requestId, RecommendationRequestStatus.Running]
  );
}

export async function markRecommendationRequestCompleted(requestId: string) {
  await query(
    `
      update recommendation_requests
      set status = $2, completed_at = now(), error_message = null
      where id = $1
    `,
    [requestId, RecommendationRequestStatus.Completed]
  );
}

export async function markRecommendationRequestFailed(requestId: string, errorMessage: string) {
  await query(
    `
      update recommendation_requests
      set status = $2, error_message = $3
      where id = $1
    `,
    [requestId, RecommendationRequestStatus.Failed, errorMessage]
  );
}

export async function createRecommendationResult(input: {
  requestId: string;
  userId: string;
  items: Array<{ id: string; itemType: "track"; rank: number }>;
}) {
  const result = await query<{ id: string }>(
    `
      insert into recommendation_results (
        recommendation_request_id,
        user_id,
        algorithm_version,
        embedding_version,
        ranking_version
      )
      values ($1, $2, $3, $4, $5)
      returning id
    `,
    [
      input.requestId,
      input.userId,
      "placeholder-worker-v1",
      "stub-embedding-v0",
      "placeholder-ranking-v1"
    ]
  );

  const row = result.rows[0];
  if (!row) {
    throw new Error("Failed to create recommendation result");
  }

  const recommendationResultId = row.id;

  for (const item of input.items) {
    await query(
      `
        insert into recommendation_result_items (
          recommendation_result_id,
          rank,
          canonical_item_type,
          canonical_item_id,
          vector_score,
          ranking_score,
          explanation
        )
        values ($1, $2, $3, $4, $5, $6, $7)
      `,
      [
        recommendationResultId,
        item.rank,
        item.itemType,
        item.id,
        1 - item.rank * 0.05,
        1 - item.rank * 0.04,
        JSON.stringify({
          reason: "Placeholder recommendation generated by worker skeleton."
        })
      ]
    );
  }
}
